import type { NewsItem } from './newsPreferences';

export const prototypeNewsItems: NewsItem[] = [
  {
    id: 'quietus-archive-electronic',
    title: 'Prototype / archival electronic reissue',
    source: 'The Quietus',
    sourceId: 'quietus',
    category: 'music',
    locality: 'international',
    tags: ['experimental', 'electronic', 'reissue', 'archive'],
    kind: 'reissue',
    baseScore: 0.92,
  },
  {
    id: 'bandcamp-contemporary-classical',
    title: 'Prototype / contemporary classical discovery',
    source: 'Bandcamp Daily',
    sourceId: 'bandcamp-daily',
    category: 'music',
    locality: 'international',
    tags: ['contemporary-classical', 'experimental', 'discovery'],
    kind: 'discovery',
    baseScore: 0.9,
  },
  {
    id: 'kulttuuritoimitus-comics-interview',
    title: 'Prototype / Finnish comics artist interview',
    source: 'Kulttuuritoimitus',
    sourceId: 'kulttuuritoimitus',
    category: 'comics',
    locality: 'finland',
    tags: ['finnish', 'comics', 'artist', 'interview'],
    kind: 'interview',
    baseScore: 0.91,
  },
  {
    id: 'archinfo-landscape-project',
    title: 'Prototype / Finnish landscape architecture project',
    source: 'Archinfo',
    sourceId: 'archinfo',
    category: 'architecture',
    locality: 'finland',
    tags: ['landscape-architecture', 'public-space', 'finnish'],
    kind: 'news',
    baseScore: 0.96,
  },
  {
    id: 'ark-urbanism-retrospective',
    title: 'Prototype / essay on Finnish urban space and planning',
    source: 'Arkkitehti',
    sourceId: 'arkkitehti',
    category: 'architecture',
    locality: 'finland',
    tags: ['urbanism', 'public-space', 'planning', 'essay'],
    kind: 'retrospective',
    baseScore: 0.94,
  },
  {
    id: 'sight-sound-restoration',
    title: 'Prototype / restored cult film returns to circulation',
    source: 'Sight and Sound',
    sourceId: 'sight-and-sound',
    category: 'film',
    locality: 'international',
    tags: ['restoration', 'archive', 'film-history'],
    kind: 'reissue',
    baseScore: 0.95,
  },
  {
    id: 'comics-journal-alternative',
    title: 'Prototype / alternative comics creator profile',
    source: 'The Comics Journal',
    sourceId: 'comics-journal',
    category: 'comics',
    locality: 'international',
    tags: ['alternative-comics', 'artist', 'independent'],
    kind: 'interview',
    baseScore: 0.88,
  },
  {
    id: 'eurogamer-design-retrospective',
    title: 'Prototype / game design retrospective',
    source: 'Eurogamer',
    sourceId: 'eurogamer',
    category: 'games',
    locality: 'international',
    tags: ['game-design', 'retrospective', 'systems'],
    kind: 'retrospective',
    baseScore: 0.77,
  },
  {
    id: 'dezeen-design-exhibition',
    title: 'Prototype / exhibition on material and industrial design',
    source: 'Dezeen',
    sourceId: 'dezeen',
    category: 'design',
    locality: 'international',
    tags: ['industrial-design', 'exhibition', 'materials'],
    kind: 'exhibition',
    baseScore: 0.78,
  },
  {
    id: 'soundi-finnish-album',
    title: 'Prototype / Finnish album and long-form artist interview',
    source: 'Soundi',
    sourceId: 'soundi',
    category: 'music',
    locality: 'finland',
    tags: ['finnish', 'album', 'artist', 'interview'],
    kind: 'interview',
    baseScore: 0.84,
  },
  {
    id: 'pitchfork-ambient-release',
    title: 'Prototype / new ambient album release',
    source: 'Pitchfork',
    sourceId: 'pitchfork',
    category: 'music',
    locality: 'international',
    tags: ['ambient', 'electronic', 'album'],
    kind: 'release',
    baseScore: 0.87,
  },
  {
    id: 'bandcamp-jazz-discovery',
    title: 'Prototype / independent jazz discovery',
    source: 'Bandcamp Daily',
    sourceId: 'bandcamp-daily',
    category: 'music',
    locality: 'international',
    tags: ['jazz', 'independent', 'discovery'],
    kind: 'discovery',
    baseScore: 0.82,
  },
  {
    id: 'kulttuuritoimitus-literature',
    title: 'Prototype / Finnish literature and cultural history essay',
    source: 'Kulttuuritoimitus',
    sourceId: 'kulttuuritoimitus',
    category: 'books',
    locality: 'finland',
    tags: ['finnish', 'literature', 'cultural-history', 'essay'],
    kind: 'review',
    baseScore: 0.81,
  },
  {
    id: 'quietus-postpunk-retrospective',
    title: 'Prototype / post-punk archival retrospective',
    source: 'The Quietus',
    sourceId: 'quietus',
    category: 'music',
    locality: 'international',
    tags: ['post-punk', 'archive', 'retrospective'],
    kind: 'retrospective',
    baseScore: 0.86,
  },
  {
    id: 'archinfo-building-heritage',
    title: 'Prototype / Finnish modern building heritage question',
    source: 'Archinfo',
    sourceId: 'archinfo',
    category: 'architecture',
    locality: 'finland',
    tags: ['building-heritage', 'modernism', 'finnish'],
    kind: 'news',
    baseScore: 0.89,
  },
  {
    id: 'sight-sound-film-history',
    title: 'Prototype / essay revisiting an overlooked film movement',
    source: 'Sight and Sound',
    sourceId: 'sight-and-sound',
    category: 'film',
    locality: 'international',
    tags: ['film-history', 'essay', 'archive'],
    kind: 'retrospective',
    baseScore: 0.85,
  },
  {
    id: 'eurogamer-indie-release',
    title: 'Prototype / small studio releases an unusual systems-driven game',
    source: 'Eurogamer',
    sourceId: 'eurogamer',
    category: 'games',
    locality: 'international',
    tags: ['indie', 'game-design', 'systems'],
    kind: 'release',
    baseScore: 0.76,
  },
  {
    id: 'itsnicethat-graphic-design',
    title: 'Prototype / graphic design and illustration studio profile',
    source: "It's Nice That",
    sourceId: 'its-nice-that',
    category: 'design',
    locality: 'international',
    tags: ['graphic-design', 'illustration', 'studio'],
    kind: 'interview',
    baseScore: 0.79,
  },
];
