name: Lockfile generation

on:
  push:
    branches:
      - ci/reproducible-checks

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0

      - name: Generate lockfile
        run: npm install --package-lock-only --ignore-scripts

      - name: Upload lockfile
        uses: actions/upload-artifact@v4
        with:
          name: generated-package-lock
          path: package-lock.json
